---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llllllll
  labels:
    app: llllllll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llllllll
  template:
    metadata:
      labels:
        app: llllllll
    spec:
      containers:
        - name: llllllll
          image: docker.io/phengbunath/llllllll:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
